// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIvqyqsHHMyQpZkj4WbE02j5OiCtPmN8',
    appId: '1:196073452206:web:8b4bf36dbd001bd377f33f',
    messagingSenderId: '196073452206',
    projectId: 'maps-b44fa',
    authDomain: 'maps-b44fa.firebaseapp.com',
    storageBucket: 'maps-b44fa.appspot.com',
    measurementId: 'G-K9SB7YEJC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2d0DonttbKnObFcDTUCqMuztisbO9RI',
    appId: '1:196073452206:android:a49102b5a63e5a6877f33f',
    messagingSenderId: '196073452206',
    projectId: 'maps-b44fa',
    storageBucket: 'maps-b44fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakSEmOM18GsAmZYR3km8zGVG461sxgIs',
    appId: '1:196073452206:ios:660cbfa28ff9015d77f33f',
    messagingSenderId: '196073452206',
    projectId: 'maps-b44fa',
    storageBucket: 'maps-b44fa.appspot.com',
    iosClientId: '196073452206-gamjfbd5enrfb1e170d9ntvj9bqp2js6.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBakSEmOM18GsAmZYR3km8zGVG461sxgIs',
    appId: '1:196073452206:ios:660cbfa28ff9015d77f33f',
    messagingSenderId: '196073452206',
    projectId: 'maps-b44fa',
    storageBucket: 'maps-b44fa.appspot.com',
    iosClientId: '196073452206-gamjfbd5enrfb1e170d9ntvj9bqp2js6.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMaps',
  );
}
